---
title: "Indicator 3 - Amount of posture changes by time unit"
author: "Mathilda Alhamadah"
date: "2025-06-18"
output:
  html_document:
    toc: true             #table des matières
    toc_float: true       #table des matières toujours visible
    theme: bootstrap      #changer le thème de la page
    highlight: zenburn    #changer le thème des chunks
    
editor_options: 
  markdown: 
    wrap: 80
---

```{r}
library(jsonlite)
library(purrr)
library(curl)
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(patchwork)
```

```{r}
load("reliable_data_8h_21h_05_07_to_08_08_2022.RData")
```

## 1.3 Amount of posture changes by time unit

### 1.3.1 Function

posture_no_na is a temporary variable : every not_visible & NA posture will be
replaced by the previous one. Useful only to count the amount of posture
changes.

```{r}
# Function 1 : Detect time changes

amount_posture_changes <- function(
    data,
    time_seconds){ 
  
  # Temporary variable : not_visible & NAs replaced by NAs
  data <- data %>% 
    mutate(posture_no_NA = case_when(
      name == "not visible" ~ NA,  #NA if not visible
      is.na(name) ~ NA,            #NA if NA
      TRUE ~ name)                 #else : posture name
      )  
  
  # Refill NAs (= real NAs + not_visible) with latest posture seen
  data <- data %>%
    fill(posture_no_NA)           
  
  
  # Detect position changes
  data_valid <- data %>%
    arrange(Date_Time) %>%  #Sort by date
    # Movement : if posture != posture at previous time (skip NAs & not_visible)
    mutate(Position_change = posture_no_NA != lag(posture_no_NA, default = first(posture_no_NA)))

  # Final dataset
  result <- changes_by_group_time(data_valid, time_gap = time_seconds)
  
  # Remove data if too many NAs
    
    
      # Set the allowed % of NAs depending on time intervals
    if(time_seconds < 3600){      #if groups < 1h
      proportion_NA <- 0.05               #max 5% of NA
    }else{
      proportion_NA <- 0.5                #else : max 50% of NA
    }
    
      # Maximum amount of NAs by interval, depending on interval length
    max_na <- floor(time_seconds*proportion_NA) #round if not integer
    
      # If too much NAs in interval : interval is NA
    result <- result %>% 
      mutate(Nb_changes = ifelse(Nb_NA > max_na, NA, Nb_changes)) 
    
      # If the time_group starts at 21h, set value to NA because there is only 1 data (maximum)
      # Other way to do : provide creating a time group starting at 21h because maximum 1 data
    result[hour(result$Time_group)==21,]$Nb_changes <- NA
    
      # Return result
      return(result)
  
  }



# Function 2 : Get the sum of posture changes by time unit

changes_by_group_time <- function(data, time_gap) {
  data %>%
    arrange(Date_Time) %>% #order by date & time
    
    #make time groups
    mutate(Time_group =
             as.POSIXct(floor                   # floor = to give the same value to all the dates that should be in the same time group
                        (as.numeric(Date_Time)  #convert every date into a number
                          / time_gap)           #so that doing +1 = changing of interval
                                   * time_gap,  #group dates by time_gap intervals
      origin = "1970-01-01")) %>% #convert numbers back to dates (origin = the reference date used by POSIXct. It was also used as a reference when we did as.numeric(Date_Time), but it was implicit)
    
    group_by(Time_group) %>%      #create groups
    summarise(                    #to make only 1 line per group & sum up the informations of all the lines
      Nb_changes = sum(Position_change, na.rm = TRUE), #number of changes = sum of changes
      Nb_NA = sum(is.na(name))                         #sum NAs
    ) %>%
    ungroup()               #always ungroup after group_by
}


```


```{r}
# Changes per 15minutes
amount_changes_15min_data_8h_21h_05_07_to_08_08_2022 <- amount_posture_changes(reliable_data_8h_21h_05_07_to_08_08_2022, 900)
```


### 1.3.2 Chart : Skip parts between 21h and 8h

```{r}
  # Add a new time variable to replace the real time

add_compressed_time_variable <- function(data) {
  data$compressed_time <- seq_len(nrow(data))-1
  return(data)
}
```

```{r}
 # Dataset

amount_changes_15min_data_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(amount_changes_15min_data_8h_21h_05_07_to_08_08_2022)
```


```{r}
  # Plot
ggplot(amount_changes_15min_data_8h_21h_05_07_to_08_08_2022_compressed_time,
       aes(x = compressed_time, y = Nb_changes)) +
  
  geom_line() +
  xlab("Time between 8h and 21h each day") +
  ylab("Amount of posture changes") +
  ggtitle("Posture changes for fox 4313", subtitle = "From 05/07 to 08/08 2022, every 15 minutes") 
```

```{r}

  # Plot

ggplot(amount_changes_15min_data_8h_21h_05_07_to_08_08_2022_compressed_time,
       aes(x = compressed_time, y = Nb_changes)) +

  
  geom_line() +
  #xlab("Temps entre 8h et 21h chaque jour") +
  ylab("Nombre de changements de position") +
  ggtitle("Changements de position du renard 4313", subtitle = "Du 4 au 6 juillet 2022, toutes les 15 minutes") 
```

