---
title: "Indicator 1 - Number & proportion of posture/ time period"
author: "Mathilda Alhamadah"
date: "2025-06-18"
output:
  html_document:
    toc: true             #table des matières
    toc_float: true       #table des matières toujours visible
    theme: bootstrap      #changer le thème de la page
    highlight: zenburn    #changer le thème des chunks
    
editor_options: 
  markdown: 
    wrap: 80
---

```{r}
library(jsonlite)
library(purrr)
library(curl)
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(patchwork)
```

```{r}
load("reliable_data_8h_21h_05_to_14_07_2022.Rdata")
```

# Indicator 1.1 : Number & proportion of each posture by time unit

## 1 Functions

```{r}
# Frequency of postures lying/ sitting/ standing by timestep (chosen)

frequency_position <- function(data, interval_seconds) {
  data <- data %>% arrange(Date_Time) #sort by date
  
  start_time <- min(data$Date_Time)   #oldest frame
  end_time <- max(data$Date_Time)     #newest frame
  
  #cut between these 2 frames depending on the time interval
  intervals <- seq(from = start_time, to = end_time, by = interval_seconds)
  
  df_counts <- data.frame(                       #create the new df
    start_time = intervals[-length(intervals)],  #drop the last time
    end_time = intervals[-1]                     #drop the first time
  )
  
  df_counts <- df_counts %>%
    rowwise() %>%               #for each line
    mutate(
      lying = sum(data$Date_Time >= start_time & data$Date_Time < end_time & data$class_id == 0),            #count lying
      standing = sum(data$Date_Time >= start_time & data$Date_Time < end_time & data$class_id == 1),            #count standing
      sitting = sum(data$Date_Time >= start_time & data$Date_Time < end_time & data$class_id == 2),            #count sitting
      not_visible = sum(data$Date_Time >= start_time & data$Date_Time < end_time & data$class_id == 3)             #count not visible
    )
  
  return(df_counts)
}
```

```{r}
# Pivot the data : 4 lines/time unit

pivot_data <- function(data,
                       variables_to_drop,       #useless variables
                       variables_to_merge,      #variables we want to merge into 1 var
                       str_name_merged_labels,  #column of the former colnames : rename
                       str_name_merged_values){  #column of the former values : rename
  
  data <- data %>% 
    select (-{{variables_to_drop}}) %>%   #eg : column end_time
    pivot_longer(
      cols = {{variables_to_merge}},      #eg : all the columns except start_time
      names_to = str_name_merged_labels,  #eg : "Posture" for the former lying/standing/...
      values_to = str_name_merged_values  #eg : "Count" for the former amounts of lying/...
    )
} 


```


```{r}
  #Remove data between 21h-8h

filter_8h_21h <- function(data, time_column){
  data <- data %>% 
    filter(hour({{time_column}}) >= 8 & hour({{time_column}}) < 21)
  return(data)
}
```

```{r}
# Add the compressed time variable to to replace the real time in order to skip the 21h-8h gap
# Needs to repeat each number 4 times because of the 4 possible postures

add_compressed_time_variable_PIVOT_data <- function(data, nbrep) {
  data$compressed_time <- rep(seq_len(nrow(data)/nbrep)-1, each = nbrep)
  return(data)
}
```

```{r}
# Proportions : pour chaque groupe de temps on veut le Count divisé par le nombre de secondes, et le reste NA/ pas noté ?

add_proportion <- function(data,
                           count_variable,    #variable of the count for each time period
                           period_duration) { #in seconds
  data <- data %>% 
    mutate(proportion = {{count_variable}}/{{period_duration}}) #proportion = count/total time
}

```

For plots only :
```{r}
  #Areas to color
  #Areas we want to color

#blue : no data available (corrupted videos)
#purple : out of the cage to put him the implant
#red : active
#green : inactive

#15min :

areas_15min <- data.frame(
  xmin = c(0, 43, 96,
           11, 21, 53, 109,
           36, 57, 113,
           15),
  xmax = c(11, 53, 109,
           15, 28, 57, 113,
           43, 62, 124,
           21),
  fill = c("No data", "No data", "No data",
           "Inactive", "Inactive", "Inactive", "Inactive",
           "Active", "Active", "Active",
           "Out for implant")
)

#30 min :
areas_30min <- data.frame(
  xmin = c(0, 21, 47,
           5, 10, 26, 53,
           18, 28, 55,
           7),
  xmax = c(5, 26, 53,
           7, 14, 28, 55,
           21, 30, 61,
           10),
  fill = c("No data", "No data", "No data",
           "Inactive", "Inactive", "Inactive", "Inactive",
           "Active", "Active", "Active",
           "Out for implant")
)

#1 hour :
areas_1h <- data.frame(
  xmin = c(0, 10, 23,
           2,5,13,26,
           9,14,27,
           3),
  xmax = c(2, 13, 26,
           3, 7, 14, 27,
           10, 15, 30,
           5),
  fill = c("No data", "No data", "No data",
           "Inactive", "Inactive", "Inactive", "Inactive",
           "Active", "Active", "Active",
           "Out for implant")
)
```


## 2 Barplot with gaps

```{r}
# Test for 900 seconds (15 minutes)

frequency_position_6h_05_to_14_07_2022 <- frequency_position(data = reliable_data_8h_21h_05_to_14_07_2022, interval_seconds = 21600)
```

```{r}
frequency_position_15min_05_to_14_07_2022_PIVOT <- pivot_data(data = frequency_position_15min_05_to_14_07_2022,
                   variables_to_drop = end_time,
                   variables_to_merge = c(lying, standing, sitting, not_visible),
                   str_name_merged_labels = "Posture",
                   str_name_merged_values = "Count")
```

```{r}
# Chart for count
ggplot(data = frequency_position_15min_05_to_14_07_2022_PIVOT,
       aes(fill = Posture, y = Count, x = start_time)) +         #start_time as x variable
  geom_bar(position = "stack", stat = "identity") +              #stacked bars, no %
  ggtitle("Fox4313's posture every 15min between days 04/07/2022 and 14/07/2022") +   #title
  xlab("Time of the day") +
  ylab("Amount of seconds spent in this posture") +                              
  scale_fill_manual(breaks = c("lying", "sitting", "standing", "not_visible"), #re-order legend
                    values = c("lying" = "lightgreen", #change legend colors
                               "sitting" = "orange",
                               "standing" = "tomato",
                               "not_visible" = "lightgrey"))
```

## 3 Barplot without gaps



```{r}
frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT <- filter_8h_21h(frequency_position_15min_05_to_14_07_2022_PIVOT, start_time)

rm(frequency_position_15min_05_to_14_07_2022_PIVOT)  #remove data with the 21h-8h gap

```

```{r}
frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT_compressed_time <- add_compressed_time_variable_PIVOT_data(frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT, nbrep = 4)

#remove useless data : no compressed time
rm(frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT)
```

```{r}
# Chart for count
ggplot(data = frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT_compressed_time,
       aes(fill = Posture, y = Count, x = compressed_time)) +         #start_time as x variable
  geom_bar(position = "stack", stat = "identity") +              #stacked bars, no %
  ggtitle("Fox4313's posture every 15min between days 04/07/2022 and 14/07/2022") +   #title
  xlab("Time of the day") +
  ylab("Amount of seconds spent in this posture") +                              
  scale_fill_manual(breaks = c("lying", "sitting", "standing", "not_visible"), #re-order legend
                    values = c("lying" = "chartreuse3", #change legend colors
                               "sitting" = "orange",
                               "standing" = "tomato",
                               "not_visible" = "lightgrey"))

```

```{r}
# Same chart but with 1 posture at a time

  #lying
ggplot(data = frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "lying"),
       aes(x = compressed_time, y = Count, fill = Posture)) +
  geom_bar(stat = "identity") +
  ggtitle("Fox4313's posture every 15min between days 04/07/2022 and 14/07/2022") +   #title
  xlab("Time of the day") +
  ylab("Amount of seconds spent in this posture") +   
  scale_fill_manual(breaks = "lying",
                    values = "chartreuse3")

  #sitting
ggplot(data = frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "sitting"),
       aes(x = compressed_time, y = Count, fill = Posture)) +
  geom_bar(stat = "identity") +
  ggtitle("Fox4313's posture every 15min between days 04/07/2022 and 14/07/2022") +   #title
  xlab("Time of the day") +
  ylab("Amount of seconds spent in this posture") +   
  scale_fill_manual(breaks = "sitting",
                    values = "orange")

  #standing
ggplot(data = frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "standing"),
       aes(x = compressed_time, y = Count, fill = Posture)) +
  geom_bar(stat = "identity") +
  ggtitle("Fox4313's posture every 15min between days 04/07/2022 and 14/07/2022") +   #title
  xlab("Time of the day") +
  ylab("Amount of seconds spent in this posture") +   
  scale_fill_manual(breaks = "standing",
                    values = "tomato")

  #not visible
ggplot(data = frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "not_visible"),
       aes(x = compressed_time, y = Count, fill = Posture)) +
  geom_bar(stat = "identity") +
  ggtitle("Fox4313's posture every 15min between days 04/07/2022 and 14/07/2022") +   #title
  xlab("Time of the day") +
  ylab("Amount of seconds spent in this posture") +   
  scale_fill_manual(breaks = "not_visible",
                    values = "darkgrey")
  
```


## 4 Lineplots without 21h-8h gaps


```{r}
# Test

frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT_compressed_time<- add_proportion(frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT_compressed_time,
                      count_variable = Count,
                      period_duration = 900)  #15 mintues by time period = 900 seconds

```

Getting the colored areas :

```{r}
  #Areas we want to color

#blue : no data available (corrupted videos)
#purple : out of the cage to put him the implant
#red : active
#green : inactive

areas_15min <- data.frame(
  xmin = c(0, 43, 96,
           11, 21, 53, 109,
           36, 57, 113,
           15),
  xmax = c(11, 53, 109,
           15, 28, 57, 113,
           43, 62, 124,
           21),
  fill = c("No data", "No data", "No data",
           "Inactive", "Inactive", "Inactive", "Inactive",
           "Active", "Active", "Active",
           "Out for implant")
)

```

```{r}
# Automatization but NOT WORKING (because pivot data, see in indicator 2 how it's done) 


# # Function
# 
# get_areas_color <- function(data, times_vector_xmin, times_vector_xmax, fill) {
#   # S'assurer que le vecteur de temps est au format POSIXct
#   times_vector_xmin <- as.POSIXct(times_vector_xmin)
#   times_vector_xmax <- as.POSIXct(times_vector_xmax)
# 
#   # Initialiser le vecteur de résultats
#   result_min <- vector("numeric", length(times_vector_xmin))
#   result_max <- vector("numeric", length(times_vector_xmax))
# 
#   # Pour chaque temps, trouver la ligne correspondante
#   for (i in seq_along(times_vector_xmin)) {
#     time_min <- times_vector_xmin[i]
#     matched_row_min <- data %>%
#       filter(start_time <= time_min & end_time >= time_min)
# 
#     # Si une ligne correspond, extraire compressed_time
#     if (nrow(matched_row_min) > 0) {
#       result_min[i] <- matched_row_min$compressed_time[1]
#     } else {
#       result_min[i] <- NA  # Aucun match trouvé
#     }
#   }
# 
#   # Pour chaque temps, trouver la ligne correspondante
#   for (i in seq_along(times_vector_xmax)) {
#     time_max <- times_vector_xmax[i]
#     matched_row_max <- data %>%
#       filter(start_time <= time_max & end_time >= time_max)
# 
#     # Si une ligne correspond, extraire compressed_time
#     if (nrow(matched_row_max) > 0) {
#       result_max[i] <- matched_row_max$compressed_time[1]
#     } else {
#       result_max[i] <- NA  # Aucun match trouvé
#     }
#   }  
#   
#   df_areas <- data.frame(xmin = result_min, xmax = result_max, fill = fill)
#   
#   return(df_areas)
# }
# 
# 
# 
# # Get areas
# 
#   areas <- get_areas_color(data = frequency_position_04_to_12_07_2022,
#                             times_vector_xmin =
#                               c("2022-07-04 08:00:00", #No data
#                                 "2022-07-04 18:57:00",
#                                 "2022-07-05 18:57:00",
#                                 "2022-07-04 10:47:00", #Inactive
#                                 "2022-07-04 13:17:00",
#                                 "2022-07-05 08:13:00",
#                                 "2022-07-06 08:50:00",
#                                 "2022-07-04 17:07:00", #Active
#                                 "2022-07-05 09:13:00",
#                                 "2022-07-06 09:50:00",
#                                 "2022-07-04 11:56:00"),#Out for implant
#                             times_vector_xmax = 
#                               c("2022-07-04 10:47:00", #No data
#                                 "2022-07-05 08:13:00",
#                                 "2022-07-06 08:50:00",
#                                 "2022-07-04 11:56:00", #Inactive
#                                 "2022-07-04 15:08:00",
#                                 "2022-07-05 09:13:00",
#                                 "2022-07-06 09:50:00",
#                                 "2022-07-04 18:57:00", #Active
#                                 "2022-07-05 10:22:00",
#                                 "2022-07-06 12:31:00",
#                                 "2022-07-04 13:17:00"),#Out for implant
#                             fill =
#                               c("No data", "No data", "No data",
#                                 "Inactive", "Inactive", "Inactive", "Inactive",
#                                 "Active", "Active", "Active",
#                                 "Out for implant"))
```


Plots :

```{r}


  # Counts
ggplot(frequency_position_15min_8h_21h_05_to_14_07_2022_PIVOT_compressed_time,
       
       aes(x = compressed_time, y = Count)) +
  geom_line(aes(color=
                  factor(Posture,
                         #re-order the labels
                         levels = c("lying", "sitting", "standing", "not_visible")))) +
  
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c("lying", "sitting", "standing", "not_visible"),
                     values = c("lying" = "chartreuse3", #change legend colors
                               "sitting" = "orange",
                               "standing" = "tomato",
                               "not_visible" = "lightgrey"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every hour") 


  # Frequencies
ggplot(frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time,

       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color= factor(Posture,
                         #re-order the labels
                         levels = c("lying", "sitting", "standing", "not_visible")))) +
  
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c("Lying", "Sitting", "Standing", "Not visible"),
                     values = c("lying" = "chartreuse3", #change legend colors
                               "sitting" = "orange",
                               "standing" = "tomato",
                               "not_visible" = "lightgrey")) +
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every 15 minutes") 


```
# Indicator 1.2 : Individual plots

Only frequencies in this one

```{r}
# Frequencies

  # Lying
ggplot(frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "lying"),
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Posture,
                         #re-order the labels
                         levels = c("lying", "sitting", "standing", "not_visible")))) +
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  scale_color_manual(name = "Posture",
                     labels = "lying",
                     values = c("lying" = "chartreuse3"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in this posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every hour") 


  # Sitting
ggplot(frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "sitting"),
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Posture,
                         #re-order the labels
                         levels = c("lying", "sitting", "standing", "not_visible")))) +
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  scale_color_manual(name = "Posture",
                     labels = "sitting",
                     values = c("sitting" = "orange"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in this posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every hour") 


  # Standing
ggplot(frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "standing"),
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Posture,
                         #re-order the labels
                         levels = c("lying", "sitting", "standing", "not_visible")))) +
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  scale_color_manual(name = "Posture",
                     labels = "standing",
                     values = c("standing" = "tomato"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in this posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every hour") 


  # Not visible
ggplot(frequency_position_8h_21h_04_to_14_07_2022_PIVOT_compressed_time %>% 
         filter(Posture == "not_visible"),
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Posture,
                         #re-order the labels
                         levels = c("lying", "sitting", "standing", "not_visible")))) +
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  scale_color_manual(name = "Posture",
                     labels = "not_visible",
                     values = c("not_visible" = "darkgrey"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in this posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every hour") 
```

# Indicator 1.3 : Standing & sitting vs lying & not visible

## time = 15min

```{r}
# Load the data
load("data_8h_21h_04_to_14_07_2022.Rdata")

# Compute the frequency of each posture
frequency_position_04_to_14_07_2022_15min <- frequency_position(data = data_8h_21h_04_to_14_07_2022, interval_seconds = 900)

# Sum the standing & sitting occurences
frequency_position_04_to_14_07_2022_StandingSitting_15min <- frequency_position_04_to_14_07_2022_15min %>% 
  mutate(sitting_standing = sum(sitting, standing),
         lying_not_visible = sum(lying, not_visible)) #maybe useless but maybe not

# Pivot the data
frequency_position_04_to_14_07_2022_StandingSitting_15min_PIVOT <- pivot_data(data = frequency_position_04_to_14_07_2022_StandingSitting_15min,
                   variables_to_drop = c(end_time, lying, sitting, standing, not_visible),
                   variables_to_merge = c(sitting_standing, lying_not_visible),
                   str_name_merged_labels = "Aggregated_postures",
                   str_name_merged_values = "Count")

# Keep only the 8h-21h part
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_15min_PIVOT <- filter_8h_21h(frequency_position_04_to_14_07_2022_StandingSitting_15min_PIVOT, start_time)
# Remove useless
rm(frequency_position_04_to_14_07_2022_StandingSitting_15min_PIVOT)  #remove data with the 21h-8h gap

# Add a compressed_time variable
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_15min_PIVOT_compressed_time <- add_compressed_time_variable_PIVOT_data(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_15min_PIVOT, nbrep = 2)

# Add a proportion variable
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_15min_PIVOT_compressed_time<- add_proportion(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_15min_PIVOT_compressed_time,
                      count_variable = Count,
                      period_duration = 900)  #15 mintues by time period = 900 seconds


```


```{r}
# Plots 




  # Counts
ggplot(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time,
       
       aes(x = compressed_time, y = Count)) +
  geom_line(aes(color=
                  factor(Aggregated_postures,
                         #re-order the labels
                         levels = c("sitting_standing", "lying_not_visible")))) +
  
  geom_rect(data = areas_15min, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c( "sitting_standing", "lying_not_visible"),
                     values = c("sitting_standing" = "tomato",
                               "lying_not_visible" = "chartreuse3"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Amount of seconds spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every 15 minutes") 



  # Frequencies
ggplot(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time,
       
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Aggregated_postures,
                         #re-order the labels
                         levels = c("sitting_standing", "lying_not_visible")))) +
  
  geom_rect(data = areas_15min, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c( "sitting_standing", "lying_not_visible"),
                     values = c("sitting_standing" = "tomato",
                               "lying_not_visible" = "chartreuse3"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Time proportion spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every 15 minutes")



  # Only sitting_standing indicator (Frequencies)

ggplot(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time %>% 
         filter(Aggregated_postures == "sitting_standing"),
       
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Aggregated_postures,
                         #re-order the labels
                         levels = c("sitting_standing")))) +
  
  geom_rect(data = areas_15min, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c( "sitting_standing"),
                     values = c("sitting_standing" = "black"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Time proportion spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every 15 minutes")

```
## time = 30min

```{r}
# Load the data
load("data_8h_21h_04_to_14_07_2022.Rdata")

# Compute the frequency of each posture
frequency_position_04_to_14_07_2022_30min <- frequency_position(data = data_8h_21h_04_to_14_07_2022, interval_seconds = 1800)

# Sum the standing & sitting occurences
frequency_position_04_to_14_07_2022_StandingSitting_30min <- frequency_position_04_to_14_07_2022_30min %>% 
  mutate(sitting_standing = sum(sitting, standing),
         lying_not_visible = sum(lying, not_visible)) #maybe useless but maybe not

# Pivot the data
frequency_position_04_to_14_07_2022_StandingSitting_PIVOT_30min <- pivot_data(data = frequency_position_04_to_14_07_2022_StandingSitting_30min,
                   variables_to_drop = c(end_time, lying, sitting, standing, not_visible),
                   variables_to_merge = c(sitting_standing, lying_not_visible),
                   str_name_merged_labels = "Aggregated_postures",
                   str_name_merged_values = "Count")

# Keep only the 8h-21h part
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_30min <- filter_8h_21h(frequency_position_04_to_14_07_2022_StandingSitting_PIVOT_30min, start_time)
# Remove useless
rm(frequency_position_04_to_14_07_2022_StandingSitting_PIVOT_30min)  #remove data with the 21h-8h gap

# Add a compressed_time variable
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_30min <- add_compressed_time_variable_PIVOT_data(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_30min, nbrep = 2) #nbrep = 2 because 2 variables : sitting/standing & lying/not_visible

# Add a proportion variable
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_30min<- add_proportion(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_30min,
                      count_variable = Count,
                      period_duration = 1800)  #15 mintues by time period = 900 seconds
```


```{r}

  # Only sitting_standing indicator (Frequencies)

ggplot(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_30min %>% 
         filter(Aggregated_postures == "sitting_standing"),
       
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Aggregated_postures,
                         #re-order the labels
                         levels = c("sitting_standing")))) +
  
  geom_rect(data = areas_30min, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c( "sitting_standing"),
                     values = c("sitting_standing" = "black"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Time proportion spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every 30 minutes")

```

## time = 1h

```{r}
# Load the data
load("data_8h_21h_04_to_14_07_2022.Rdata")

# Compute the frequency of each posture
frequency_position_04_to_14_07_2022_1h <- frequency_position(data = data_8h_21h_04_to_14_07_2022, interval_seconds = 3600)

# Sum the standing & sitting occurences
frequency_position_04_to_14_07_2022_StandingSitting_1h <- frequency_position_04_to_14_07_2022_1h %>% 
  mutate(sitting_standing = sum(sitting, standing),
         lying_not_visible = sum(lying, not_visible)) #maybe useless but maybe not

# Pivot the data
frequency_position_04_to_14_07_2022_StandingSitting_PIVOT_1h <- pivot_data(data = frequency_position_04_to_14_07_2022_StandingSitting_1h,
                   variables_to_drop = c(end_time, lying, sitting, standing, not_visible),
                   variables_to_merge = c(sitting_standing, lying_not_visible),
                   str_name_merged_labels = "Aggregated_postures",
                   str_name_merged_values = "Count")

# Keep only the 8h-21h part
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_1h <- filter_8h_21h(frequency_position_04_to_14_07_2022_StandingSitting_PIVOT_1h, start_time)
# Remove useless
rm(frequency_position_04_to_14_07_2022_StandingSitting_PIVOT_1h)  #remove data with the 21h-8h gap

# Add a compressed_time variable
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_1h <- add_compressed_time_variable_PIVOT_data(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_1h, nbrep = 2) #nbrep = 2 because 2 variables : sitting/standing & lying/not_visible

# Add a proportion variable
frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_1h<- add_proportion(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_1h,
                      count_variable = Count,
                      period_duration = 3600)  #15 mintues by time period = 900 seconds
```


```{r}

  # Only sitting_standing indicator (Frequencies)

ggplot(frequency_position_8h_21h_04_to_14_07_2022_StandingSitting_PIVOT_compressed_time_1h %>% 
         filter(Aggregated_postures == "sitting_standing"),
       
       aes(x = compressed_time, y = proportion)) +
  geom_line(aes(color=
                  factor(Aggregated_postures,
                         #re-order the labels
                         levels = c("sitting_standing")))) +
  
  geom_rect(data = areas_1h, aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, alpha = 0.2) +
  
  scale_color_manual(name = "Posture",
                     labels = c( "sitting_standing"),
                     values = c("sitting_standing" = "black"))+
  scale_x_continuous(name = "Time between 8h and 21h each day",
                     breaks = c(0,50, 100, 150, 200, 250, 300, 350, 400, 450, 500)) +
  ylab("Time proportion spent in each posture") +
  ggtitle("Postures of fox fox 4313", subtitle = "From 4 to 14 of July 2022, every hour")

```


