---
title: "Prise en main de Git sur Rstudio"
author: "Mathilda Alhamadah"
date: "2025-03-21"
output: html_document
---

# Commit, Push et Pull

Commit = pour faire une nouvelle sauvegarde EN LOCAL Push (flèche qui monte) = après plusieurs commit, pour les envoyer sur le remote EN CLOUD Pull (flèche qui descend) = pour récupérer la version qui est sur le remote

Bonne pratique travail à plusieurs : toujours Pull avant de Push, pour développer son amélioration du code sur la dernière version du code des autres.

Conseil : Commiter très régulièrement pour avoir des traces de toutes les modifs et pouvoir y revenir. Pusher dès qu'on a une version stable, pour que chaque Push soit un truc propre duquel on peut repartir.  
-> Moi avec mon petit Rmd qui est juste de la prise de notes c'est stable tout le temps, donc je peux Push à chaque fois que je commit. 

# Le fichier .gitignore

Le fichier .gitignore c'est pour demander à Git de pas prendre en compte certains fichiers pour les commit. Boarf pas utile pour le moment je pense

# Créer une nouvelle branche et merge

Créer une nouvelle branche avec l'icône violette. Puis on peut commit et push dedans.

Quand on est satisfait de la branche et qu'on veut la merge dans le main, on fait une Pull Request sur GitHub Bonne pratique travail à plusieurs : ne pas valider sa propre pull request, pour faire vérifier son code par qqn ! Mais là projet solo : on valide.

Pour supprimer les changements non comités et revenir au dernier comit de la branche : alt+maj+R puis : git reset --hard

Après avoir merge une branche avec le main, pour que ça apparaisse, il faut pull.

# Checkout

Le checkout : pour revenir à l'état du projet d'il y a quelques jours pour y développer une novuelle branche. Pour se repositionner sur un commit particulier, il faut trouver son hash. Pour ça : cliquer sur le fichier -\> history (l'horloge) -\> le numéro qui apparaît en face de chaque commit est le hash, ou SHA.

Ensuite, copier le hash et faire alt+maj+R puis : git checkout numero_du_hash

Si on veut faire des modifs depuis ce comit, il faut y **créer une branche**, sinon on perd le contact entre ce qu'on est en train de développer (qui sera un genre de nouveau main) et le main de base : bourbier !

# /!\\ Repository public

Maintenant je peux aller sur Insights -\> Network pour voir un joli dessin de mon arborescence :)

# Supprimer une branche

Sur GitHub afficher toutes les branches et cliquer sur la poubelle en face de la branche à supprimer.

Moi je supprime la branche Essai v0 parce que c'était juste pour faire des tests.

# Renommer un fichier

J'avais appelé ce fichier **Essai v0** parce que je pensais le supprimer rapidement mais en fait il me fait un bon mémo, alors je veux l'appeler **Memo_Git**. Du coup pour le renommer :

-   alt+maj+R puis : git mv ancien_nom_fichier nouveau_nom_fichier (et bien mettre l'extention dans le nom du fichier)

-   commiter le changement : git commit -m "Renommé ancien_nom_fichier en nouveau_nom_fichier" (ça c'est pour set le msg à afficher pour le commit)

-   push le changement vers GitHub : git push origin main

Je pense qu'on peut le faire en clic bouton mais au moins j'ai la procédure en code.

/!\\ C'est hyper bourbier de faire des noms de fichiers avec des espaces, pcq qd on les appelle depuis le terminal ça fait tout planter ! Utiliser des underscore.\
Sinon : faire les commandes du terminal avec des guillemets autour du nom du fichier

/!\\/!\\ Ne **pas oublier l'extension** du fichier sinon c'est juste un texte et on peut plus rien en faire !
Après avoir renommé le fichier, le **fermer immédiatement** et ouvrir le nouveau sinon on redéveloppe dans le même fichier pas renommé ! 

# Liens & ressources utiles

-   Le site grâce auquel j'ai pu tout installer & configurer : <https://thinkr.fr/travailler-avec-git-via-rstudio-et-versionner-son-code/>
-   Un cheatsheet pour se rappeler des grandes étapes : <https://danielkummer.github.io/git-flow-cheatsheet/index.fr_FR.html>
