---
title: "Shewhart indicator 2"
author: "Mathilda Alhamadah"
date: "2025-07-21"
output: html_document
---

# 0. Starter

```{r}
library(qcc)
library(jsonlite)
library(purrr)
library(curl)
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(patchwork)
```


# 1. Load data

You can load the data here :
```{r}
load("data_QCC_indicator2_complete_reliable_15min_to_6h.RData")
```

## → How to get this data ?

Load the data without days of anesthesia and without non reliable data :

```{r}
load("reliable_data_8h_21h_05_07_to_08_08_2022.RData")
```

Create the code for each posture : 
```{r}
# Change posture code to lying < sitting < standing (instead of lying < standing < sitting)
posture_123 <- function(data){
  data <- data %>% 
  mutate(increasing_code = case_when(name=="lying" ~ 0,
                                   name=="sitting" ~ 1,
                                   name=="standing" ~ 2,
                                   name=="not visible" ~ NA, #to avoid having it in the sum
                                   TRUE ~ NA)) #if none of the 4 above (normally doesn't happen), then NA
}
```

```{r}
# Apply function
reliable_data_8h_21h_05_07_to_08_08_2022_posture_code <- posture_123(reliable_data_8h_21h_05_07_to_08_08_2022)
```

Create the activity score :
```{r}
# Amount activity function
amount_activity <- function(data, interval_seconds) {
  data <- data %>% arrange(Date_Time)
  
  start_time <- min(data$Date_Time)
  end_time <- max(data$Date_Time)
  
  intervals <- seq(from = start_time, to = end_time, by = interval_seconds)
  
  df_counts <- data.frame(
    interval_start = intervals[-length(intervals)],
    interval_end = intervals[-1]
  )
  
  df_counts <- df_counts %>%
    rowwise() %>%
    mutate(
      # Filter without NA values to compute the total_activity score
      valid_values = list(data$increasing_code[data$Date_Time >= interval_start & data$Date_Time < interval_end & !is.na(data$increasing_code)]),
      total_activity = sum(valid_values,
                           na.rm = FALSE) / 2, # Divide by 2 to get a max of 1. There should not be any NA remaining.
      # Compute the number of not NA values
      no_na_count = length(valid_values),
      # Compute the activity_proportion score depending on not NA values
      activity_proportion = ifelse(no_na_count > 0, total_activity / no_na_count, NA)
    ) %>%
    select(-valid_values, -no_na_count) # Remove temporary columns
  
  return(df_counts)
}

```

```{r}
# Apply function

  #15min
activity_score_15min_05_07_to_08_08_2022 <- amount_activity(data = reliable_data_8h_21h_05_07_to_08_08_2022_posture_code,
                                                                        interval_seconds = 900)

  #30min
activity_score_30min_05_07_to_08_08_2022 <- amount_activity(data = reliable_data_8h_21h_05_07_to_08_08_2022_posture_code,
                                                                        interval_seconds = 1800)

  #1h
activity_score_1h_05_07_to_08_08_2022 <- amount_activity(data = reliable_data_8h_21h_05_07_to_08_08_2022_posture_code,
                                                                        interval_seconds = 3600)

  #2h
activity_score_2h_05_07_to_08_08_2022 <- amount_activity(data = reliable_data_8h_21h_05_07_to_08_08_2022_posture_code,
                                                                        interval_seconds = 7200)

  #4h
activity_score_4h_05_07_to_08_08_2022 <- amount_activity(data = reliable_data_8h_21h_05_07_to_08_08_2022_posture_code,
                                                                        interval_seconds = 14400)

  #6h
activity_score_6h_05_07_to_08_08_2022 <- amount_activity(data = reliable_data_8h_21h_05_07_to_08_08_2022_posture_code,
                                                                        interval_seconds = 21600)

# Remove useless data
rm(reliable_data_8h_21h_05_07_to_08_08_2022_posture_code)
```

Remove again the 21h-8h gap :

```{r}
# Function to remove the 21h-8h gap that has been re-created by the amount_activity function
filter_8h_21h <- function(data, time_column){
  data <- data %>% 
    filter(hour({{time_column}}) >= 8 & hour({{time_column}}) < 21)
  return(data)
}
```

```{r}
# Apply function

  #15min
activity_score_15min_8h_21h_05_07_to_08_08_2022 <- filter_8h_21h(data = activity_score_15min_05_07_to_08_08_2022,
                                                              time_column = interval_start)

  #30min
activity_score_30min_8h_21h_05_07_to_08_08_2022 <- filter_8h_21h(data = activity_score_30min_05_07_to_08_08_2022,
                                                              time_column = interval_start)

  #1h
activity_score_1h_8h_21h_05_07_to_08_08_2022 <- filter_8h_21h(data = activity_score_1h_05_07_to_08_08_2022,
                                                              time_column = interval_start)
  
  #2h
activity_score_2h_8h_21h_05_07_to_08_08_2022 <- filter_8h_21h(data = activity_score_2h_05_07_to_08_08_2022,
                                                              time_column = interval_start)

  #4h
activity_score_4h_8h_21h_05_07_to_08_08_2022 <- filter_8h_21h(data = activity_score_4h_05_07_to_08_08_2022,
                                                              time_column = interval_start)

  #6h
activity_score_6h_8h_21h_05_07_to_08_08_2022 <- filter_8h_21h(data = activity_score_6h_05_07_to_08_08_2022,
                                                              time_column = interval_start)
  
  
# Remove useless data :
rm(activity_score_15min_05_07_to_08_08_2022, activity_score_30min_05_07_to_08_08_2022, activity_score_1h_05_07_to_08_08_2022, activity_score_2h_05_07_to_08_08_2022, activity_score_4h_05_07_to_08_08_2022, activity_score_6h_05_07_to_08_08_2022)

```

Create a variable to replace time & skip gaps :

```{r}
# Useful to skip the 21h-8h gap when plotting/ analyzing
add_compressed_time_variable <- function(data) {
  data$compressed_time <- seq_len(nrow(data))-1 #-1 to make it start with 0
  return(data)
}
```

```{r}
# Apply function

  #15min
activity_score_15min_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(activity_score_15min_8h_21h_05_07_to_08_08_2022)

  #30min
activity_score_30min_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(activity_score_30min_8h_21h_05_07_to_08_08_2022)

  #1h
activity_score_1h_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(activity_score_1h_8h_21h_05_07_to_08_08_2022)
  
  #2h
activity_score_2h_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(activity_score_2h_8h_21h_05_07_to_08_08_2022)

  #4h
activity_score_4h_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(activity_score_4h_8h_21h_05_07_to_08_08_2022)

  #6h
activity_score_6h_8h_21h_05_07_to_08_08_2022_compressed_time <- add_compressed_time_variable(activity_score_6h_8h_21h_05_07_to_08_08_2022)
  
rm(activity_score_15min_8h_21h_05_07_to_08_08_2022, activity_score_30min_8h_21h_05_07_to_08_08_2022, activity_score_1h_8h_21h_05_07_to_08_08_2022, activity_score_2h_8h_21h_05_07_to_08_08_2022, activity_score_4h_8h_21h_05_07_to_08_08_2022, activity_score_6h_8h_21h_05_07_to_08_08_2022)
```

Add a day variable to aggregate :

```{r}
activity_score_15min_8h_21h_05_07_to_08_08_2022_compressed_time <- activity_score_15min_8h_21h_05_07_to_08_08_2022_compressed_time %>%
  mutate(day = as.Date(interval_start))

activity_score_30min_8h_21h_05_07_to_08_08_2022_compressed_time <- activity_score_30min_8h_21h_05_07_to_08_08_2022_compressed_time %>%
  mutate(day = as.Date(interval_start))

activity_score_1h_8h_21h_05_07_to_08_08_2022_compressed_time <- activity_score_1h_8h_21h_05_07_to_08_08_2022_compressed_time %>%
  mutate(day = as.Date(interval_start))

activity_score_2h_8h_21h_05_07_to_08_08_2022_compressed_time <- activity_score_2h_8h_21h_05_07_to_08_08_2022_compressed_time %>%
  mutate(day = as.Date(interval_start))

activity_score_4h_8h_21h_05_07_to_08_08_2022_compressed_time <- activity_score_4h_8h_21h_05_07_to_08_08_2022_compressed_time %>%
  mutate(day = as.Date(interval_start))

activity_score_6h_8h_21h_05_07_to_08_08_2022_compressed_time <- activity_score_6h_8h_21h_05_07_to_08_08_2022_compressed_time %>%
  mutate(day = as.Date(interval_start))
```

And we finally have the data : 
```{r}
load("data_QCC_indicator2_complete_reliable_15min_to_6h.RData")
```



# 2. Aggregate by day

```{r}
# Function to do it
aggregate_by_day_2 <- function(activity_score_data_list = list(activity_score_15min_8h_21h_05_07_to_08_08_2022_compressed_time,
                                                              activity_score_30min_8h_21h_05_07_to_08_08_2022_compressed_time,
                                                              activity_score_1h_8h_21h_05_07_to_08_08_2022_compressed_time,
                                                              activity_score_2h_8h_21h_05_07_to_08_08_2022_compressed_time,
                                                              activity_score_4h_8h_21h_05_07_to_08_08_2022_compressed_time,
                                                              activity_score_6h_8h_21h_05_07_to_08_08_2022_compressed_time) ,
                               times_vector = c("15min", "30min", "1h", "2h", "4h", "6h")) {
  
  for(i in seq(1,6,1)) { #for i in 1:6
    
    variable_name <- paste("activity_score_byday", times_vector[i], sep = "_") #create variable name : activity_score_byday_time
    assign(variable_name, qcc.groups(data = activity_score_data_list[[i]]$activity_proportion, #qcc groups on every dataset
                                   sample = activity_score_data_list[[i]]$day),                #aggregate by day
         envir = .GlobalEnv)    #put it in global environment directly
    
  }
}
```

```{r}
# Apply function
aggregate_by_day_2()
```



# 3. Xbar chart


```{r}
#Plot xbar charts for sitting_standing postures

  #timesteps = 15min, 1point = 1day
qcc(data = activity_score_byday_15min[1:10,], #5 first days = calibration
    type = "xbar",               #chart type
    newdata = activity_score_byday_15min[32:35,])  #5-11 days = test phase


  #timesteps = 30min, 1point = 1day
qcc(data = activity_score_byday_30min[1:10,], #5 first days = calibration
    type = "xbar",               #chart type
    newdata = activity_score_byday_30min[32:35,]) #5-11 days = test phase


  #timesteps = 1h, 1point = 1day
qcc(data = activity_score_byday_1h[1:10,], #5 first days = calibration
    type = "xbar",               #chart type
    newdata = activity_score_byday_1h[32:35,]) #5-11 days = test phase

  #timesteps = 2h, 1point = 1day
qcc(data = activity_score_byday_2h[1:10,], #5 first days = calibration
    type = "xbar",               #chart type
    newdata = activity_score_byday_2h[32:35,])  #5-11 days = test phase


  #timesteps = 4h, 1point = 1day
qcc(data = activity_score_byday_4h[1:4,], #5 first days = calibration
    type = "xbar",               #chart type
    newdata = activity_score_byday_4h[32:35,]) #5-11 days = test phase
```




















