---
title: "Shewhart indicator 3"
author: "Mathilda Alhamadah"
date: "2025-07-21"
output: html_document
---

# 0. Starter

```{r}
library(jsonlite)
library(purrr)
library(curl)
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(patchwork)
```

# 1. Load data

```{r}

```


## → How to get this data ?

```{r}
load("reliable_data_8h_21h_05_07_to_08_08_2022.RData")
```

```{r}
# Function 1 : Detect time changes

amount_posture_changes <- function(
    data,
    group_time){ #group_time : "number + unit" (among : second, minute, hour, day,                     week, month, bimonth, quarter, season, halfyear and year)
  
  # Temporary variable : not_visible & NAs replaced by NAs
  data <- data %>% 
    mutate(posture_no_NA = case_when(
      name == "not visible" ~ NA,  #NA if not visible
      is.na(name) ~ NA,            #NA if NA
      TRUE ~ name)                 #else : posture name
      )  
  
  data <- data %>%
    fill(posture_no_NA)           #refill NAs (= real NAs + not_visible) with latest posture seen
  
  
  # Detect position changes
  data_valid <- data %>%
    arrange(Date_Time) %>%  #Sort by date
    # Movement : if posture != posture at previous time (skip NAs & not_visible)
    mutate(Position_change = posture_no_NA != lag(posture_no_NA, default = first(posture_no_NA)))

  # Results
  return(changes_by_group_time(data_valid, time_gap = group_time))
  }



# Function 2 : Get the sum of posture changes by time unit

changes_by_group_time <- function(data, time_gap) {
  data %>%
    mutate(Time_group = floor_date(Date_Time, unit = time_gap)) %>% #make time groups
    group_by(Time_group) %>%
    summarise(Nb_changes = sum(Position_change, na.rm = TRUE)) %>% #sum changes
    ungroup()                                     #just in case
}

```


# 2. Aggregate by day

# 3. Xbar chart